name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Install dependencies
        run: dotnet restore src/IsAwaitable/IsAwaitable.csproj
      - name: Build
        run: dotnet build src/IsAwaitable/IsAwaitable.csproj -c Release --no-restore

  test-netcore:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: Tests netstandard2.1 on .NET Core 3.1
        run: |
          dotnet build src/IsAwaitable/IsAwaitable.csproj -c Release --framework netstandard2.1
          dotnet build tests/IsAwaitable.Tests/IsAwaitable.Tests.csproj -c Release --framework netcoreapp3.1
          dotnet test --no-build --verbosity normal -c Release --framework netcoreapp3.1
      - name: Tests netstandard2.0 on .NET Core 2.1
        run: |
          dotnet build src/IsAwaitable/IsAwaitable.csproj -c Release --framework netstandard2.0
          dotnet build tests/IsAwaitable.Tests/IsAwaitable.Tests.csproj -c Release --framework netcoreapp2.1
          dotnet test --no-build --verbosity normal -c Release --framework netcoreapp2.1

  test-netframework:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Tests netstandard2.0 on .NET Framework 4.6.1
        run: |
          dotnet build src/IsAwaitable/IsAwaitable.csproj -c Release --framework netstandard2.0
          dotnet build tests/IsAwaitable.Tests/IsAwaitable.Tests.csproj -c Release --framework net461
          dotnet test --no-build --verbosity normal -c Release --framework net461

  coverage:
    if: ${{ github.event_name == 'push' }}
    needs: [test-netcore, test-netframework]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet build -c Debug src/IsAwaitable/IsAwaitable.csproj
      - run: dotnet build -c Debug tests/IsAwaitable.Tests/IsAwaitable.Tests.csproj --framework netcoreapp3.1
      - name: Collect coverage
        run: dotnet test -c Debug --framework netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=lcov
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage.info
          path: tests/IsAwaitable.Tests/coverage/coverage.netcoreapp3.1.info
      - name: Upload to Coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: tests/IsAwaitable.Tests/coverage/coverage.netcoreapp3.1.info
