name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Setup tests for coverage report
        run: |
          echo "Install minicover"
          dotnet tool install --global minicover
          echo "Setup tests"
          minicover instrument
          minicover reset
      - name: Test
        run: |
          echo "Run tests"
          dotnet test --configuration Release --no-build --verbosity normal
          echo "Release tests from code coverage setup"
          minicover uninstrument
      - name: Upload coverage
        env:
          COVERALL_REPO_TOKEN: ${{ secrets.COVERALL_REPO_TOKEN }}
          JOB_ID: ${{ github.run_id }}
        run: |
          last_commit_id=$(git rev-parse HEAD)
          minicover coverallsreport --repo-token "$COVERALL_REPO_TOKEN" --service-name "github" --service-job-id "$JOB_ID" --branch "main" --commit "$last_commit_id"
