name: Pack

on:
  push:
    branches: [main]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - run: dotnet restore src/IsAwaitable/IsAwaitable.csproj
      - run: dotnet build src/IsAwaitable/IsAwaitable.csproj -c Release --framework net5.0 --no-restore
      - name: Install requirements
        run: |
          sudo apt-get install -y unzip
          sudo apt-get install -y xmlstarlet
          sudo apt-get install -y zip
      - name: Create package
        working-directory: ./pack
        run: sudo ./pack_isawaitable.sh
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            pack/*.nupkg
            pack/*.snupkg
